# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TEST(object):
    def setupUi(self, TEST):
        TEST.setObjectName("TEST")
        TEST.resize(634, 455)
        TEST.setMaximumSize(QtCore.QSize(634, 455))
        TEST.setStyleSheet("")
        self.pushButton = QtWidgets.QPushButton(TEST)
        self.pushButton.setGeometry(QtCore.QRect(30, 380, 131, 51))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_3 = QtWidgets.QPushButton(TEST)
        self.pushButton_3.setGeometry(QtCore.QRect(480, 380, 131, 51))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_2 = QtWidgets.QPushButton(TEST)
        self.pushButton_2.setGeometry(QtCore.QRect(260, 380, 131, 51))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_4 = QtWidgets.QPushButton(TEST)
        self.pushButton_4.setGeometry(QtCore.QRect(30, 280, 131, 51))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_2 = QtWidgets.QLabel(TEST)
        self.label_2.setGeometry(QtCore.QRect(0, -8, 641, 471))
        self.label_2.setMaximumSize(QtCore.QSize(1024, 768))
        self.label_2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_2.setObjectName("label_2")
        self.label_2.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.pushButton_4.raise_()


        self.retranslateUi(TEST)
        QtCore.QMetaObject.connectSlotsByName(TEST)

    def retranslateUi(self, TEST):
        _translate = QtCore.QCoreApplication.translate
        TEST.setWindowTitle(_translate("TEST", "Form"))
        self.pushButton.setText(_translate("TEST", "EXTRACT"))
        self.pushButton_2.setText(_translate("TEST", "LOAD"))
        self.pushButton_3.setText(_translate("TEST", "TRANSFORM"))
        self.pushButton_4.setText(_translate("TEST", "EXIT"))
        self.label_2.setText(_translate("TEST", "<html><head/><body><p><img src=\":/newPrefix/1429682.png\"/></p></body></html>"))

import first_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TEST = QtWidgets.QWidget()
    ui = Ui_TEST()
    ui.setupUi(TEST)
    TEST.show()
    sys.exit(app.exec_())
